---

- name: Make selinux permissive
  selinux: policy=targeted state=permissive

- name: Enable epel repo
  yum: name=epel-release state=present
 
- name: Install lbzip2 required to extract iRedMail
  yum: name=lbzip2 state=present

- name: Check if iredmail is already installed
  stat: path=/opt/iRedMail
  register: iredmail_installed

- name: Download and extract iRedMail
  unarchive:
    src={{ iredmail_url }}
    dest=/opt/
    copy=no
