---

- name: Make selinux permissive
  selinux: policy=targeted state=permissive

- name: Check if iredmail is already installed
  stat: path=/opt/iRedMail*
  register: iredmail_installed

- name: Download and extract the latest iRedMail
  unarchive: 
    src=https://bitbucket.org/zhb/iredmail/downloads/iRedMail-0.9.5.tar.bz2 
    dest=/opt/ 
    copy=no 
  when: not iredmail_installed.stat.exists
